name: Python CI pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Run Unit Tests
      run: python -m unittest discover

    - name: Create ZIP if tests pass
      run: zip balicek.zip skript.py
